### ISSUE TITLE
The types folder is not flow checked

### ISSUE THREAD

**Issue by ColinEberhardt** [xtuc/webassemblyjs#145]
We have our 'global' type definitions within the `src\flow` folder, which is references in the `[libs]` section of `.flowconfig`.

As a result of this, the typing within these files is not being checked. For example, the AST typing refers to a `Byte` type which is not defined anywhere:

https://github.com/xtuc/js-webassembly-interpreter/blob/master/src/types/AST.js#L250

You can verify that this is an issue by just randomly deleting type definitions. e.g. if you delete this line:

https://github.com/xtuc/js-webassembly-interpreter/blob/master/src/types/AST.js#L3

the flow checks still pass.

I think there are two potential resolutions:

1. Does Flow have a setting where you can specify a library definition that flow actually type-checks?
2. Move these type definitions outside of the `[libs]` setting - although this probably means that we'd have to explicitly import types each time we use them.

**Comment by xtuc** [comment]
Interesting, I might have ignored the type folder in eslint (can't find it on mobile sorry) because it complains that none of them are used. 

Sometimes I notice that when you have a parse error in that file flow fails silently, it's quite annoying.

**Comment by ColinEberhardt** [comment]
> Interesting, I might have ignored the type folder in eslint (can't find it on mobile sorry) because it complains that none of them are used.

Ah - I hadn't checked the eslint ignore file, you're right, that folder is ignored. I'll see if I can find a fix.

Unfortunately my previous typed-JS experience has all been with TypeScript, which is subtly different in the way that these things are configured!

**Comment by xtuc** [comment]
Ok, so I think that the fix would be to not ignore the folder and add some rules on top of the file, what do you think?

It's my bad, I could have make that experience better from the beginning.

**Comment by ColinEberhardt** [comment]
no problem - I'll try to fix this shortly after finishing off data segment / string parser

**Comment by xtuc** [comment]
Fixed by https://github.com/xtuc/webassemblyjs/commit/e4dfc316a682895e326e3ae7f2b9d6f95f311090
