### ISSUE TITLE
Decode i64 in WASM

### ISSUE THREAD

**Issue by xtuc** [xtuc/webassemblyjs#169]
Following https://github.com/xtuc/js-webassembly-interpreter/pull/167/files/e9929cbbac66dc791574083ea4cfc17261b0cdbb#r170259102

Currently we represent it has a JS number, which doesn't cover the entire 64 bits range, see:

https://github.com/xtuc/js-webassembly-interpreter/blob/e9929cbbac66dc791574083ea4cfc17261b0cdbb/src/compiler/parsing/wasm/decoder.js#L38-L43

I would propose to use the two's complement representation once we have the decode LEB128 buffer.

**Comment by xtuc** [comment]
Turns out that the `leb` package we're using doesn't support it.

https://github.com/brodybits/leb/blob/22f054f7668e317b5ee9a3a26ca3b3b43d49a364/lib/leb.js#L249-L251

I'll need to fork it to allow returning a two's complement representation to into our `LongNumberLiteral`.

**Comment by maurobringolf** [comment]
Am I understanding this right: the `leb` package always returns a JS number for a parsed 64 bit integer? So you would add a `decodeInt64ToLong` (or similar) function that returns a Long instead?

**Comment by xtuc** [comment]
Yeah, I don't know why `leb` is doing that, but that's how it works.

**Comment by maurobringolf** [comment]
Maybe open an issue and ask if they can provide a loss free decoder which returns [hi, lo] instead?

**Comment by xtuc** [comment]
I had considered that but:
- The last commit is from 6 years ago
- They have disabled the issue tracker lol

That's why I mentioned that we should fork it instead.
