### ISSUE TITLE
Converting WASM to AST

### ISSUE THREAD

**Issue by karthikrish9** [xtuc/webassemblyjs#195]
Hi  @xtuc ,

I have a WASM binary. Is there anyway I can convert one of the exported function 
of the WASM binary to AST? Any help to do this is appreciated. 

Regards,
Karthik

**Comment by xtuc** [comment]
Yes sure, sorry if this project is lacking some useful documentation currently.

Here's an example:

```js
import { decode } from "@webassemblyjs/wasm-parser";
import { traverse } from "@webassemblyjs/ast";

const ast = decode(bin);

let exportedId;

// Find the exported function
t.traverse(ast, {
    ModuleExport({ node }) {
      if (node.descr.type === "Func") {
        exportedId = node.descr.id;
      }
    }
});

// Search the function now
t.traverse(ast, {
    Func({ node }) {
      if (node.name && node.name.value === exportedId.value) {
        console.log(node); // Here's your function node
      }
    }
});
```

Also make sure to use the Decoder options https://github.com/xtuc/webassemblyjs/tree/master/packages/wasm-parser#decoder-options if you don't need to access those sections.

**Comment by xtuc** [comment]
I'm closing this, feel free to re-open or comment if needed.
