### ISSUE TITLE
different AST produced for ModuleExport from wasm / wat parser

### ISSUE THREAD

**Issue by ColinEberhardt** [xtuc/webassemblyjs#218]
Given the following wat:

```
(export "test" (func 1))
```

The WAT parser creates this AST:

```
          {
            "type": "ModuleExport",
            "name": "test",
            "descr": {
              "type": "Func",
              "id": {
               "type": "NumberLiteral",
               "value": 1,
               "raw": "1"
              }
            }
          }
```

However, converting this wat to wasm, via wabt, then parsing with th ewasm-parser, the following AST is generated:

```
          {
            "type": "ModuleExport",
            "name": "test",
            "descr": {
              "type": "Func",
              "id": {
               "type": "Identifier",
               "value": "func_2"
              }
            }
          }
```

Which is correct?

The wasm parser output looks more logical to me!

**Comment by maurobringolf** [comment]
Probably related to https://github.com/xtuc/webassemblyjs/blob/master/docs/contrib-transform-wast-identifier-to-index.md. I think functions need to be identified by index (numberLiteral) and only the wast script syntax adds the syntax sugar for referencing by name? I am not sure though.

**Comment by ColinEberhardt** [comment]
I think this is a different issue. The wast-identified-to-index transformation can be done by reading the custom name section:

https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#name-section

I'm half way through implementing that here: https://github.com/xtuc/webassemblyjs/pull/212 - I've implemented the logic that converts function names from indices back to their label names, need to add the same logic for locals.

In this case `(export "test" (func 1))` the string `test` is visible in the AST for both the wasm and wat parser - it's how we encode the `(func 1)` part that differs.

**Comment by maurobringolf** [comment]
Hmm okay, can you explain why the second one makes more sense to you? I'm confused because this references the function at index `1` which does not exist here. So why would it be renamed to "func_2"? Sorry if I am confusing things!

**Comment by ColinEberhardt** [comment]
> I'm confused because this references the function at index 1 which does not exist here. So why would it be renamed to "func_2"? Sorry if I am confusing things!

Sorry - this is just a fragment of the AST, both reference functions by index (the fact the one has an index of '1' and the other is '2' is not relevant).

The thing I want to clarify is whether references to functions should be nodes of type `NumberLiteral` (as per the the WAT parser), or an `Identifier`(as per the WASM parser).

The identifier / index transform and differences in index (1 vs. 2) are things I can happily resolve.

**Comment by maurobringolf** [comment]
Ahhh thanks! I didnt get that `func_2` refers to the same thing as `func 2`. Makes sense, its a question of encoding in the AST.

**Comment by ColinEberhardt** [comment]
To summarise a quick chat I had with @xtuc - the interpreter uses indices for these references, which is why the wast-parser currently converts to an index based approach. However, the AST should be a simple representation of the wat / wasm, without too much additional processing (otherwise it becomes hard to round trip e.g. wat -> ast -> wat), therefore references should not be converted into indices.

As a result, module exports should reference functiosn via a node of `Identifier` type.

Here's an example:

```
(module
  (func)
  (export "test" (func 0))
)
```

Transforms to:

```
  {
    "type": "Program",
    "body": [
      {
        "type": "Module",
        "id": null,
        "fields": [
          {
            "type": "Func",
            "name": {
              "type": "Identifier",
              "value": "func_0"
            },
            "params": [],
            "result": [],
            "body": []
          },
          {
            "type": "ModuleExport",
            "name": "test",
            "descr": {
              "type": "Func",
              "id": {
                 "type": "Identifier",
                 "value": "func_0"
              }
            }
          }
        ]
      }
    ]
  }
```
