### ISSUE TITLE
preserve raw values of identifiers

### ISSUE THREAD

**Issue by ColinEberhardt** [xtuc/webassemblyjs#228]
Continuing from this comment https://github.com/xtuc/webassemblyjs/pull/225#discussion_r178530364

The following WAST file:

```
(module (table 0 anyfunc) (export "a" (table 0)))
```

Generates the given AST:

```
  {
    "type": "Program",
    "body": [
      {
        "type": "Module",
        "id": null,
        "fields": [
          {
            "type": "Table",
            "elementType": "anyfunc",
            "limits": {
              "type": "Limit",
              "min": "0"
            },
            "name": {
              "type": "Identifier",
              "value": "table_0"
            }
          },
          {
            "type": "ModuleExport",
            "name": "a",
            "descr": {
              "type": "Table",
              "id": {
                "type": "Identifier",
                "value": "table_0"
              }
            }
          }
        ]
      }
    ]
  }
```

Should we always preserve the raw values for identifiers? In other words, when generating a unique name, also include the integer index? If so, this would result in the following AST:

```
  {
    "type": "Program",
    "body": [
      {
        "type": "Module",
        "id": null,
        "fields": [
          {
            "type": "Table",
            "elementType": "anyfunc",
            "limits": {
              "type": "Limit",
              "min": "0"
            },
            "name": {
              "type": "Identifier",
              "value": "table_0",
                "raw": 0                     <----------
            }
          },
          {
            "type": "ModuleExport",
            "name": "a",
            "descr": {
              "type": "Table",
              "id": {
                "type": "Identifier",
                "value": "table_0",
                "raw": 0                     <----------
              }
            }
          }
        ]
      }
    ]
  }
```

**Comment by xtuc** [comment]
@ColinEberhardt you said that this is for clarification, do you any input or questions about it?

I don't think it's a big change, we just need to make sure to keep the original value around. Which will be used exclusively for printing.

Note that the `raw` field is a string.

**Comment by ColinEberhardt** [comment]
> @ColinEberhardt you said that this is for clarification, do you any input or questions about it?

If you're happy with the example AST above, that's all the clarification needed!

> Note that the raw field is a string.

Good point.

Note to self - a raw encoding would make the logic for re-instating identifier names a little simpler: https://github.com/xtuc/webassemblyjs/blob/master/packages/wasm-parser/src/index.js#L33
