### ISSUE TITLE
Number Literal syntax issue

### ISSUE THREAD

**Issue by xtuc** [xtuc/webassemblyjs#251]
```wat
(module
  (func
    (i32.const ++-----1)
  )
)
```

shouldn't be valid, only one +/- is allowed.

**Comment by maurobringolf** [comment]
I'll take it :+1:

**Comment by xtuc** [comment]
Thanks, are you planning to add it to the FSM?

**Comment by xtuc** [comment]
yes, and after_sign is basically a number.

**Comment by maurobringolf** [comment]
Exactly, After sign is the current `START` state without the sign transition :+1:
