### ISSUE TITLE
Correct node locations

### ISSUE THREAD

**Issue by xtuc** [xtuc/webassemblyjs#252]
In general location in the AST are pretty inaccurate (my bad), we should fix it in the tokenizer.

Example https://github.com/xtuc/webassemblyjs/blob/b1197bf8f3329c73193437af08d94887899eac3b/packages/wast-parser/test/fixtures/func/invalid-result/throws.txt

**Comment by maurobringolf** [comment]
You mean line/column for sourcemaps?

**Comment by xtuc** [comment]
Yes, I had more error messages in mind, but sourcemaps is even worst if you have bad locations.

**Comment by xtuc** [comment]
Good point. We can iterate after your PR lands. If you return a node in the error message we have a location to point to.
