### ISSUE TITLE
Getting 404 when trying to install was-parser package

### ISSUE THREAD

**Issue by aleybovich** [xtuc/webassemblyjs#292]
I run
```
npm install @webassemblyjs/wasm-parser
```

I get this error:
```
npm ERR! code E404
npm ERR! 404 Not Found: @webassemblyjs/wasm-parser@latest
```

**Comment by xtuc** [comment]
That's strange, the package exist on npm: https://www.npmjs.com/package/@webassemblyjs/wasm-parser

Are you using a private registry or use a proxy?

**Comment by aleybovich** [comment]
I just noticed I'm having issues with some other packages as well, must be my proxy settings. I'll close this issue, looks like it's a user error :) Sorry for taking your time.
