### ISSUE TITLE
Locals in wasm-parser

### ISSUE THREAD

**Issue by maurobringolf** [xtuc/webassemblyjs#302]
It seems like locals are not handled correctly in wasm-parser currently. Here is what I tried as a new testcase:

```
(module
  (func (result i64)
  	(local i32)
    (get_local 0)
  )
)
```

And here is what I get:

![image](https://user-images.githubusercontent.com/18613301/39881462-53432516-5481-11e8-9fc0-f5fbd33dce54.png)

**Comment by ColinEberhardt** [comment]
I intend to get back to broadening the wasm parser test fixtures in the near future - at the moment it doesn’t have much coverage

**Comment by maurobringolf** [comment]
Great! I'm also focusing on this parser instead of wast-parser now since it is used a lot more :+1:
