### ISSUE TITLE
Allow instruction without parentheses

### ISSUE THREAD

**Issue by xtuc** [xtuc/webassemblyjs#339]
The following example should be parsed:

```wast
(func (i32.const 1) drop)
```

But we currently disallow the an instruction (`drop` here) without parentheses. 

This is fine:
```wast
(func (i32.const 1) (drop))
```

---

We need to use the instruction signatures to know when to stop to parse an instruction, for example:

```wast
(func i32.const 1 drop)
```

is valid too.

**Comment by maurobringolf** [comment]
Ill have a go at this

**Comment by xtuc** [comment]
We have a first support in https://github.com/xtuc/webassemblyjs/pull/343.
