### ISSUE TITLE
AST remove() function doesn't work for nodes with multiple child node properties

### ISSUE THREAD

**Issue by ColinEberhardt** [xtuc/webassemblyjs#350]
The current remove function relies on being able to remove a node given its parent:

https://github.com/xtuc/webassemblyjs/blob/master/packages/ast/src/traverse.js#L7

However, a number of nodes have multiple properties which can themselves contain child nodes, e.g. `ModuleMetadata`

**Comment by xtuc** [comment]
Yes I agree, the way it works currently is probably not the best. Also I believe we can have a generic approach which would cover both `path.remove` and `path.replaceWith` (remove is a remplacement with nothing).
