### ISSUE TITLE
Add licenses and urls to all package.json

### ISSUE THREAD

**Issue by mlucool** [xtuc/webassemblyjs#351]
Hi,

For all subrepos, please update the urls and licenses and possibly a short readme. For example: https://github.com/xtuc/webassemblyjs/blob/master/packages/leb128/package.json is missing both, so [on npm](https://www.npmjs.com/package/@webassemblyjs/leb128) it looks like this which is a little scary until you google:
![image](https://user-images.githubusercontent.com/1813603/40544787-11512df2-6047-11e8-9135-9498396d4754.png)

**Comment by xtuc** [comment]
Some packages are intentionally not documented because they are meant for internal use only.

**Comment by mlucool** [comment]
A doc that says "For internal use" is great too. Either way, things like auditing fail without repo location and license.

**Comment by xtuc** [comment]
Do you mind submitting a PR?

**Comment by ColinEberhardt** [comment]
I think we should just add the MIT licence to all packages - a lot of people run automated checks that would fail with packages that lack licence info

**Comment by maurobringolf** [comment]
I think it is also worth having two sentences for internal packages. Interest in the project is clearly growing and it might motivate/help future contributors.

**Comment by mlucool** [comment]
Thank you @xtuc . I was unable to get to this due to travel.
