### ISSUE TITLE
initializer expression cannot reference a mutable global

### ISSUE THREAD

**Issue by xtuc** [xtuc/webassemblyjs#355]
Found in https://github.com/webpack/webpack/pull/7404

**Comment by maurobringolf** [comment]
Would this fall into the `isConst` check? i.e.

https://github.com/xtuc/webassemblyjs/blob/master/packages/validation/src/is-const.js#L26-L28

should check the moduleContext for mutability of the global somehow?

**Comment by xtuc** [comment]
Yes that's correct. The issue is that this check is missing too much context. We should refactor it and provide the `ModuleContext`.
