### ISSUE TITLE
Upgrade flow

### ISSUE THREAD

**Issue by xtuc** [xtuc/webassemblyjs#357]
We upgraded flow recently and now we are seeing weird errors:
```
/home/travis/build/xtuc/webassemblyjs/packages/ast/src/signatures.js
  17:11  error  References:  flowtype-errors/show-errors
```

**Comment by maurobringolf** [comment]
Does this include https://travis-ci.org/xtuc/webassemblyjs/jobs/383412920? These confused me but I havent tried to fix them yet

**Comment by xtuc** [comment]
Yes exactly.
