### ISSUE TITLE
Implement atomic proposal

### ISSUE THREAD

**Issue by xtuc** [xtuc/webassemblyjs#393]
- [ ] wasm parser
- [ ] wast printer

See https://github.com/WebAssembly/threads

**Comment by martianboy** [comment]
@xtuc I'd like to implement support for the threads/atomics proposal, mainly in the `wasm-parser` package, but I can also continue the work to cover all the other modules as well. Here's a checklist of the changes I intend to make, please let me know what you think:

- [ ] [ast] Add the `shared` flag to `Limit` definition, to support shared linear memory.
- [ ] [helper-wasm-bytecode] Add two-byte atomic instruction codes starting with 0xfe.
- [ ] [wasm-parser] Support shared linear memory in `parseLimits` function.
- [ ] [wasm-parser] Support atomic instructions with the memory immediate in `parseInstructionBlock` function.

**Comment by xtuc** [comment]
That's good news @martianboy, thanks. I will be happy to help
