### ISSUE TITLE
wasm-parser -- Decode can produce unexpected module import identifier

### ISSUE THREAD

**Issue by TimHambourger** [xtuc/webassemblyjs#406]
### Description
In certain cases, `decode` can produce AST containing unexpected identifiers inside module import nodes.

### Steps to Repro
The behavior depends highly on the input .wasm file. I haven't found a good minimal repro yet, but you can use [this file](https://github.com/TimHambourger/webassemblyjs-wasm-corruption/blob/master/webassemblyjs-repro/wasm-input/get37_release_bg.wasm) as input. Note that that file was compiled in release mode from Rust src that uses [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen), then post-processed with the wasm-bindgen CLI. The Rust src is [quite trivial](https://github.com/TimHambourger/webassemblyjs-wasm-corruption/blob/master/wasm-src/get37/src/lib.rs).

With that input in hand, decode like
```js
import { decode } from '@webassemblyjs/wasm-parser';

const bin; // ArrayBuffer containing the .wasm input

const ast = decode(bin);

// Note that there's only one import in the file
const importNode = ast.body[0].fields.filter(f => f.type === 'ModuleImport')[0];
```
At this point, importNode looks like
```json
{
  "type": "ModuleImport",
  "module": "./get37",
  "name": "__wbindgen_throw",
  "descr": {
    "type": "FuncImportDescr",
    "id": {
      "type": "Identifier",
      "value": "__rust_dealloc"
    },
    "signature": {
      "type": "Signature",
      "params": [
        {
          "valtype": "i32"
        },
        {
          "valtype": "i32"
        }
      ],
      "results": []
    }
  },
  "loc": {
    "start": {
      "line": -1,
      "column": 120
    },
    "end": {
      "line": -1,
      "column": 147
    }
  }
}
```

`module` and `name` are as expected, but `descr.id` is unexpected. If you process the same input w/ [wasm2wat](https://github.com/WebAssembly/wabt), the relevant excerpts look like
```wat
(module
  (type $t5 (func (param i32 i32)))
  (import "./get37" "__wbindgen_throw" (func $__wbindgen_throw (type $t5)))
  (func $core::ptr::drop_in_place::h99e3afcc3d3d20ab (type $t0) (param $p0 i32))
  (func $__wbg_get37_free (export "__wbg_get37_free") (type $t0) (param $p0 i32)
    (drop
      (call $wasm_bindgen::convert::GlobalStack::new::hf5174142e84b82ff))
    (block $B0
      (block $B1
        (br_if $B1
          (i32.eqz
            (get_local $p0)))
        (br_if $B0
          (i32.load
            (get_local $p0)))
        (i32.store align=1
          (get_local $p0)
          (i32.const 0))
        (call $__rust_dealloc
          (get_local $p0)
          (i32.const 4)
          (i32.const 4))
        (return))
```
So you can see the `import` node and some time later the `__rust_dealloc` identifier, but unless I'm missing something `__rust_dealloc` is NOT the identifier for the import node's description.

### Expected behavior
That `importNode.descr.id.value` would be `'__wbindgen_throw'`. Unless I'm missing something.

### Remarks
Downstream, this can lead to exceptions editing import names as mentioned in #405. That repro goes like:
```js
import { edit } from '@webassemblyjs/wasm-edit';

const bin; // ArrayBuffer containing .wasm input
edit(bin, {
    ModuleImport(path) {
        path.node.name += '!!';
    }
});
```

That throws with "Unsupported node Identifier" due to the assertion in
```js
    case "FuncImportDescr":
      {
        out.push(0x00); // $FlowIgnore

        assertNotIdentifierNode(n.descr.id); // $FlowIgnore

        out.push.apply(out, _toConsumableArray(encodeU32(n.descr.id.value)));
        break;
      }
```

At that assertion, `n.descr.id.value` is `'__rust_dealloc'`.

As in #405, the exception can be avoided by `decode`ing with `ignoreCustomNameSection: true`. At that point, the output WASM seems to be what I'd expect, based on running back through wasm2wat.

**Comment by ColinEberhardt** [comment]
Thanks for the bug report - certainly looks like there could be an issue with the custom name section parsing and subsequent transformation of the AST.

Just out of interest, what is your overall goal here? is ignoring custom name sections a valid work-around in the short term?

**Comment by TimHambourger** [comment]
@ColinEberhardt Thanks for the responses! Yes, you ask a fair question about goals.

My real goal is that I'm experiencing a bug w/ wasm-edit producing corrupt/invalid output WASM. This is getting exposed bundling WASM w/ webpack. I'll file a detailed issue for that one in the next day or so. These others were smaller issues I hit along the way.

So short answer: Yes, ignoring custom name sections IS a valid work-around. Longer answer: I thought this issue in particular might be connected to the issue I'm seeing w/ output corruption. That reproes whether I ignore custom name sections or not. One thing I haven't tried yet is removing the custom name section BEFORE handing off to wasm-parser. I'll do a little more experimenting and hopefully this will all be clearer when I file that other issue.

Thanks for your help! I'll keep you posted.

**Comment by xtuc** [comment]
As @ColinEberhardt pointed out, it's likely due to the custom name section, but maybe we are parsing it incorrectly.

**Comment by TimHambourger** [comment]
Thanks @xtuc @ColinEberhardt. I just posted my other issue (#407). After spending more time, I'm less inclined to think the two are related, but I'll leave it to y'all to decide.

**Comment by ColinEberhardt** [comment]
OK, I've just got round to looking into this issue. The current logic for processing the custom name section makes certain assumptions about the generated function names. I think I've got a fix, but want to add some more tests around this code first.

**Comment by ColinEberhardt** [comment]
Ah ... getting closer! It is a problem with the import module parsing. We're using the type index as a reference to the function:

https://github.com/xtuc/webassemblyjs/blob/master/packages/wasm-parser/src/decoder.js#L435

In this case, the type index is 5, which is incorrectly being used as a function reference.
