### ISSUE TITLE
wasm-edit can trigger LEB128 warning, producing corrupt output

### ISSUE THREAD

**Issue by TimHambourger** [xtuc/webassemblyjs#407]
### Description
In some circumstances, wasm-edit can produce corrupt, non-compilable output. These cases appear to coincide with a warning, "LEB128 encoding changed, this might lead to bugs" (generated by [helper-wasm-section](https://github.com/xtuc/webassemblyjs/blob/babd73f8734dea82f8c1e617001f97af09dd2c32/packages/helper-wasm-section/src/resize.js#L42)). 

### Steps to Repro
The behavior depends on the input wasm and the edit(s) applied. [Full repro here](https://github.com/TimHambourger/webassemblyjs-wasm-corruption). Or skip straight to [test results](https://github.com/TimHambourger/webassemblyjs-wasm-corruption/blob/master/webassemblyjs-repro/fullTextResults.txt).

#### Steps to run
1. Clone the linked repo
1. Cd into the webassemblyjs-repro directory
1. Run `npm install`
1. Run `node index.js`

That will read all of the .wasm files in the wasm-input directory and apply a series of edits to each one. For each file + edit combo, the harness then tests if the output is valid WASM by a) parsing w/ wasm-parser and b) compiling w/ V8's native `WebAssembly.compile`. The harness then logs test results to console and writes all output files (valid or not) to the wasm-output directory.

Sample output (excerpted for [single input file](https://github.com/TimHambourger/webassemblyjs-wasm-corruption/blob/master/webassemblyjs-repro/wasm-input/julia_wasm_bg.wasm) and single edit):
```
running case julia_wasm_bg.wasm -- oneCharExports
LEB128 encoding changed, this might lead to bugs
julia_wasm_bg.wasm -- oneCharExports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: CompileError: WasmCompile: Wasm decoding failed: unknown section code #0x1f @+786
```

The edit applied (where bin is the input `ArrayBuffer`):
```js
function oneCharExports(bin) {
    const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
    let i = 0;
    return editWithAST(getAST(bin), bin, {
        ModuleExport(path) {
            path.node.name = chars[i++];
        }
    });
}

function getAST(bin) {
    return decode(bin, {
        // Needed to work around https://github.com/xtuc/webassemblyjs/issues/405
        ignoreCustomNameSection: true,
        // ignoreDataSection and ignoreCodeSection seem to significantly speed up the decode
        ignoreDataSection: true,
        ignoreCodeSection: true,
    });
}
```

[Results for more files](https://github.com/TimHambourger/webassemblyjs-wasm-corruption/blob/master/webassemblyjs-repro/fullTextResults.txt)

### About the Input Files
I've included several input files (hopefully not an overwhelming number), some of which expose the behavior and some of which don't.

- julia_wasm_bg.wasm -- This is the one I really care about. From a [toy project of mine](https://github.com/TimHambourger/julia-wasm) for trying out WASM + build tools (plus Rust, [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen), [surplus](https://github.com/adamhaile/surplus), fun stuff...). Note that I'm in the middle of switching to webpack's built-in WASM support, hence how I got to webassemblyjs....
- add.wasm, call.wasm -- From [MDN's examples](https://github.com/mdn/webassembly-examples/tree/master/understanding-text-format). These don't trigger the bug.
- Others -- compiled from simple [Rust src](https://github.com/TimHambourger/webassemblyjs-wasm-corruption/tree/master/wasm-src) with various build settings and post-processing steps. I'm happy to provide more detail if it's helpful.

### Observations
The corruption strongly correlates with the LEB128 warning. So far, I haven't found a way to pre-process the failing cases to avoid the warning. Also note a few cases don't trigger the warning but do still fail a wasm-parser `decode` (but not a `WebAssembly.compile`):
```
get37_debug.wasm -- addAssignExports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
```

### Environment
webassemblyjs packages -- all 1.5.13
node -- 8.9.2
OS -- OSX 10.13.5

Thanks for your help!

**Comment by TimHambourger** [comment]
@sokra FYI, you can expose this one from webpack. [Repro here](https://github.com/TimHambourger/webassemblyjs-wasm-corruption/tree/master/webpack-repro). The key steps:
1. Start w/ a .wasm file that exposes this bug.
1. Import that .wasm file synchronously into another file (which can then itself be imported dynamically). So `import(/* webpackChunkName: "myWasm" */ './myWasm')` won't expose the issue, but `import * as wasm from './myWasm'` and, in another file, `import(/* webpackChunkName: "fileThatImportsWasm" */ './fileThatImportsWasm')` will. Note that this is the [recommended way](https://rustwasm.github.io/wasm-bindgen/basic-usage.html) of using [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen) with webpack (search "import(" in the linked docs).
1. Include the `FlagDependencyUsagePlugin` in your build. This is turned on by default in production mode.

`FlagDependencyUsagePlugin` and import topology matter b/c [WebAssemblyGenerator.js](https://github.com/webpack/webpack/blob/69f03be1ea5187e681d3295e679789aa0e6364a5/lib/wasm/WebAssemblyGenerator.js#L235-L251) uses `module.isUsed` inside the `rewriteExportNames` function. If either of those conditions aren't met, then `module.isUsed` ends up returning the original export names unchanged, so `rewriteExportNames` ends up being a no-op.

#### How to Run the Repro
1. Clone the [linked repo](https://github.com/TimHambourger/webassemblyjs-wasm-corruption/)
1. Cd into webpack-repro
1. Run `npm install`
1. Run `webpack-dev-server`
1. Open in browser

Note that the browser window is blank. If you open the console, you'll see an error like "Uncaught (in promise) CompileError: AsyncCompile: Wasm decoding failed: expected 21 bytes, fell off end @+780".

If you go into webpack.config.js, comment out the `FlagDependencyUsagePlugin` invocation, restart webpack-dev-server and reload your browser, you should instead see text like "buffer addr is 0x120008".

**Comment by xtuc** [comment]
Thanks for the great report, again.

Here's how `wasm-edit` works:
1. we decode a wasm binary (preserving the Node's locations in the AST)
2. transformation(s)
3. using the diff between 1. and 2.
    - print node that changed
    - replace in the binary using the original location from 1.

Sometime we have binary that adds padding to LEB128 encoding (LLVM backend for instance). That means that number like `1` are in fact encoded like `0 0 0 0 1` , using 5 bytes instead of only 1 byte.

When the number is printed on our side we don't add the padding, and we don't exactly replace the entire sequence of bytes in the binary, and actually breaking it (often it overflows on following section, that's why you see the `unexpected section 0x0`).

Unfortunately I wasn't able to handle this case in `wasm-edit`, since we could detect it I added this warning. Webpack uses a pre-process phase https://github.com/webpack/webpack/blob/69f03be1ea5187e681d3295e679789aa0e6364a5/lib/wasm/WebAssemblyGenerator.js#L35-L38 that removes these padding beforehand. 

For now I would recommend you using the pre-process phase, even if it's quite costly, or we can try to work on this again (I can give you more details about the implementation itself).

**Comment by TimHambourger** [comment]
@xtuc Thanks for the quick response! Your explanation is helpful.

I think I'm [already](https://github.com/TimHambourger/webassemblyjs-wasm-corruption/blob/master/webassemblyjs-repro/index.js#L39) [pre-processing](https://github.com/TimHambourger/webassemblyjs-wasm-corruption/blob/master/webassemblyjs-repro/index.js#L141-L144) in the same way as webpack (a recent addition to my test suite). And I can repro the issue with webpack too. So something about my input is apparently causing the pre-process not to work as intended.

**Comment by TimHambourger** [comment]
@xtuc @ColinEberhardt OK, I submitted a PR for this. #413 plus #410 fix most of the errors from [my test suite](https://github.com/TimHambourger/webassemblyjs-wasm-corruption). (#410 matters for the case "add_long_export_name.wasm -- addAssignExports").

The remaining failing cases are
```
get37_debug.wasm -- addAssignExports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
get37_debug.wasm -- oneCharExports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
get37_debug.wasm -- removeExports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
get37_debug.wasm -- renameImports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
get37_no_struct_debug.wasm -- addAssignExports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
get37_no_struct_debug.wasm -- oneCharExports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
get37_no_struct_debug.wasm -- removeExports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
get37_no_struct_debug.wasm -- renameImports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
get37_no_struct_release.wasm -- addAssignExports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
get37_no_struct_release.wasm -- oneCharExports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
get37_no_struct_release.wasm -- removeExports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
get37_no_struct_release.wasm -- renameImports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
get37_release.wasm -- addAssignExports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
get37_release.wasm -- oneCharExports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
get37_release.wasm -- removeExports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
get37_release.wasm -- renameImports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
```
It looks like there's something separate going on with these, so I'm going to file a new issue for them and disregard them for the purposes of this issue going forward. From my POV they're also a lower priority.

**Comment by xtuc** [comment]
Thanks for the great work @TimHambourger!

**Comment by TimHambourger** [comment]
@xtuc @sokra BTW, forgot to mention: I've verified that applying this patch does indeed fix the corruption I observed with webpack.

@xtuc Thanks for being so responsive! Happy to contribute.

**Comment by xtuc** [comment]
Great! I'll publish and bump the dep in Webpack.

**Comment by xtuc** [comment]
@TimHambourger I'm not sure to understand, could we remove the warning and the `shrinkPaddedLEB128` pre-processing phase?

**Comment by TimHambourger** [comment]
@xtuc I had the same question about the warning and pre-process phase. I figured getting it to produce valid output was step 1, and getting it to do so with less noise is step 2! :)

So short answer: Yes, I think those should be safe to drop.

Long answer: Is there anywhere else you remember padded inputs causing issues? It probably makes sense to add test coverage for wasm-edit + padded inputs at the same time as dropping the warning and pre-process phase.

**Comment by xtuc** [comment]
I don't see a reason to keep the pre-processing phase, it was only used for section resizing in `wasm-edit`.

It seems that we don't have a dedicated test here, but Webpack test suite includes a couple of those binaries (and https://github.com/webpack/webpack/pull/7732 seems to pass).
