### ISSUE TITLE
Can you increment the version number?

### ISSUE THREAD

**Issue by void4** [xtuc/webassemblyjs#437]
Right now all packages refer to v1.7.4, which does not include the latest fix.

```
  "dependencies": {
    "@webassemblyjs/ast": "1.7.4",
```
I have not found a way to refer to the local path of the package without having to rewrite all the imports in the respective files across all packages.

**Comment by xtuc** [comment]
Yes, I haven't published the latest changes.

I just published https://github.com/xtuc/webassemblyjs/releases/tag/v1.7.5
