### ISSUE TITLE
wasm-strip appears to not strip all the things

### ISSUE THREAD

**Issue by Ekleog** [xtuc/webassemblyjs#439]
On the output of rustc, already wasm-gc'd, running `wasm-strip` still leaves lots of debug sections present.

See eg. http://ekleog.xelpaste.net/nOfcpG for a file that, when run `wasm-strip` on. It appears to slowly reduce the size of the file, though, when run multiple times. Also, it ends up crashing with `Error: Unexpected section: 0x1` when run one too many times.

**Comment by xtuc** [comment]
Yes, currently `wasm-strip` only strips _one_ custom section out (I know that's not ideal).

**Comment by Ekleog** [comment]
Leaving this open to track progress on this question, then :)

**Comment by Ekleog** [comment]
Thank you! :D
