### ISSUE TITLE
wasm-strip generates an invalid output

### ISSUE THREAD

**Issue by Ekleog** [xtuc/webassemblyjs#442]
When being run with [this file](http://ekleog.xelpaste.net/3M4S3w) as input (generated with `rustc`, cleaned with `wasm-gc` then a few times through `wasm-strip`), wasmgen errors with Unexpected section: 0x1

**Comment by Ekleog** [comment]
Hmm, I can confirm it generated a wrong binary, as the official `wasm` appears unable to decode it too. At first I thought it somehow didn't recognize the `types` section, defined as 0x1 in the spec, but it looks like that's not it :)

Renaming the issue to better fit the error. Unfortunately, I don't think I have the file used before generation of this one any longer, so feel free to close if you can't reproduce :)

**Comment by xtuc** [comment]
I think it's fine, it should appear on any compiled rust.
