### ISSUE TITLE
Add LICENSE files to packages/*

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [xtuc/webassemblyjs#452]
Hello,

It looks like packages/floating-hex-parser has a LICENSE file, but most of the other packages don't. Would you mind adding LICENSE files to the other packages, too?

**Comment by xtuc** [comment]
Would you mind sending a PR? We could just copy the LICENSE file at the root in each sub packages (expect those that already have one).

**Comment by Bosch-Eli-Black** [comment]
@opichals Haha, seems like maybe we're both dealing with licensing a lot lately :)

I think that updating to lerna is beyond what I may do at the moment, I'm afraid.

**Comment by xtuc** [comment]
@Bosch-Eli-Black, we did modify some of the code of the package, I guess that it's right to include the original license and publish our own package with another license (compatible with Apache 2). That's my understanding but I'm not a layer.

**Comment by pksunkara** [comment]
@xtuc I can make a PR upgrading lerna to 3 if you are okay. Not much breaking changes.

**Comment by pksunkara** [comment]
Made #455. Once you merge and publish using it, it should fix this issue.

**Comment by xtuc** [comment]
I'll confirm that we have the license once I publish a new version, I will then close it.

**Comment by Bosch-Eli-Black** [comment]
Thanks, @pksunkara!

@xtuc, Respectfully, I think that the issues with @maurobringolf as the author and the issue with Apache 2 also need to be sorted out before this is closed.


Apache 2 says that

> You must give any other recipients of the Work or Derivative Works a copy of this License; and
> You must cause any modified files to carry prominent notices stating that You changed the files; and ...

Therefore, I think that, just for the `leb128` package, the files that were modified need to have a prominent notice added to them saying that the files were changed, and the Apache 2 license file needs to present somewhere in the `leb128` package.

My understanding is that any new code that was added to the `leb128` package may be licensed under MIT, but the original portion of the code needs to be licensed in Apache 2. That sounds like a pain, though, so personally, I think just making the `leb128` package be licensed under Apache2 and having the rest of the packages be licensed under MIT would be the way to go.

I'm not a lawyer either, though :)

**Comment by xtuc** [comment]
Ok, `1.7.8` includes the licenses. I'll bump Webpack.
