### ISSUE TITLE
mamacro should be in devDependecies

### ISSUE THREAD

**Issue by xtuc** [xtuc/webassemblyjs#453]
See https://github.com/xtuc/webassemblyjs/blob/master/packages/ast/package.json#L18 and https://github.com/xtuc/mamacro/issues/2#issuecomment-421902240

**Comment by char0n** [comment]
I can provide a PR to remedy this, if it agreed that this should be acted upon.

**Comment by xtuc** [comment]
That would be great!

**Comment by char0n** [comment]
@xtuc PR provided

**Comment by Bosch-Eli-Black** [comment]
IMO, It would still be nice for mamacro to have a LICENSE file, though. Let me know if you want me to provide a PR :)
