### ISSUE TITLE
@webassemblyjs/helper-module-context missing dependency on@webassemblyjs/ast

### ISSUE THREAD

**Issue by ahimberg** [xtuc/webassemblyjs#487]
using pnpm, which does package isolation enforcing proper dependencies

with the latest @webassemblyjs packages (indirectly getting them with the webpack 4.29.4 update), getting this error
Error: Cannot find module '@webassemblyjs/ast' from helper-module-context

helper-module-context\package.json should declare a dependency on @webassemblyjs/ast

**Comment by xtuc** [comment]
would you mind sending a PR?
