### ISSUE TITLE
dependency protocol change

### ISSUE THREAD

**Issue by wangxiaodong0120** [xtuc/webassemblyjs#490]
"git://github.com/dcodeIO/long.js.git#8181a6b50a2a230f0b2a1e4c4093f9b9d19c8b69"
would you please help to change the git protocol to https, because our company just support https protocol.
thanks a lot!

**Comment by xtuc** [comment]
Duplicated of https://github.com/xtuc/webassemblyjs/issues/486, i'm working on it.
