### ISSUE TITLE
leb128 depends on the Github version of long

### ISSUE THREAD

**Issue by luishasmail** [xtuc/webassemblyjs#492]
Hello there, I recently started having issues with Webpack when trying to get a pull request through our CI pipeline. After some digging I found that the problem was that yarn was attempting to install the dependency `long` from Github instead of npm. After some digging I found that Webpack -> webassemblyjs -> webassemblyjs/leb128 -> long. Inside of leb128’s package.json I saw that long is being installed from its source on Github instead of npm. My guess is this was done to use 4.2.2 instead of 4.0.0? Our CI system only permits using packages installed from npm and as a result, this is blocking us from uptaking the latest version of Webpack.

Is it possible to switch over to the npm version of this dependency?

**Comment by xtuc** [comment]
Please use `webpack@4.29.5`

**Comment by luishasmail** [comment]
@xtuc I am running that version of Webpack. This a problem with Webpack 4.29.5.
