### ISSUE TITLE
mamacro should be a devDependency for helper-module-context

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [xtuc/webassemblyjs#578]
It looks like `mamacro` is listed as a dependency, instead of a devDependency, in https://github.com/xtuc/webassemblyjs/blob/573c38515f80d582ebebc357ace5742197450551/packages/helper-module-context/package.json

My understanding from https://github.com/xtuc/mamacro/issues/2 is that `mamacro` should only be listed as a dev dependency.

The reason why this is a problem for us is that `mamacro` doesn't have a LICENSE file, but since it's listed as a dependency instead of a devDependency, it shows up in our license scanner.

Thanks :)

**Comment by xtuc** [comment]
Good catch. Would you mind sending a PR?

**Comment by Bosch-Eli-Black** [comment]
Unfortunately, maybe not :\  I'm hoping someone else might pick this up.

Thanks for the quick reply, though :)

**Comment by momesana** [comment]
This is a big blocker and show-stopper for us. Out of over 2000 unique deps in our application mamacro is the only item lacking a suitable license (even as a devDependency it would'nt have hurt to put it under a suitable license).
