### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by selfagency** [xtuc/webassemblyjs#632]
Somehow `@webassemblyjs/ast` got installed globally on my system and every time I try to uninstall it, it just reinstalls itself:

```
➜ npm -g rm @webassemblyjs/ast --force
npm WARN using --force I sure hope you know what you are doing.
added 10 packages from 3 contributors in 0.707s

➜ npm -g ls --depth=0
/usr/local/lib
├── @webassemblyjs/ast@1.8.5
└── npm@6.10.1
```

Any idea what the heck is happening here?

**Comment by xtuc** [comment]
That's probably an error with npm not `@webassemblyjs/ast`. Have you tried to delete the files under `/usr/local/lib`?
