### ISSUE TITLE
How to generate packages/dce/src/libwabt.js?

### ISSUE THREAD

**Issue by pravi** [xtuc/webassemblyjs#668]
While trying to package webassemblyjs for debian (https://salsa.debian.org/js-team/webassemblyjs),

lintian gave this error,
E: webassemblyjs source: source-is-missing packages/dce/src/libwabt.js line length is 32768 characters (>512)

and indeed this looks like a generated file, though scripts/build.sh just copies this file from src to lib. Can you share how this file was generated? We need to provide source code for all the generated files we ship in debian.

**Comment by xtuc** [comment]
I don't want my package to be distributed by debian, the dce package is also deprecated.

**Comment by pravi** [comment]
Alright. Thanks for the reply. I have removed dce from the debian package. Since you package is a dependency of webpack, we have to include it (lots of other packages in debian uses webpack to build).
