### ISSUE TITLE
404 Error XTUC/long

### ISSUE THREAD

**Issue by prashantpiyer** [xtuc/webassemblyjs#684]
I'm not able to install other dependencies due this @xtuc/long error 
I'm using proxy and and I did npm cache clean also.
nodev: 10.17.0
npmv:6.11.3

npm http fetch GET 404 https://registry.npmjs.org/@xtuc%2flong 1517ms
npm http fetch GET 404 https://registry.npmjs.org/@xtuc%2flong 1551ms
npm verb stack RangeError: Maximum call stack size exceeded

**Comment by xtuc** [comment]
Make sure to purge the cache of your proxy. I have no control on this
