### ISSUE TITLE
Implement basic instructions linting

### ISSUE THREAD

**Issue by xtuc** [xtuc/webassemblyjs#71]
We can use static analysis to emit an early error when we are sure that it will lead to an invalid result at runtime.

Example:

```wat
(func (result i32)
  (i64.const 1)
)
```

We know that the result of `i64.const` is an `i64` and the result of the func will be `i64`, so the result is not correct.

**Comment by maurobringolf** [comment]
If I understand the spec correctly, everything described in here https://webassembly.github.io/spec/core/valid/index.html should be checked before a module is instantiated.

**Comment by xtuc** [comment]
Possible yes, tbh I didn't explore enough this part of the spec yet
