### ISSUE TITLE
@webassemblyjs-dce 1.7.11 GPL V2 license

### ISSUE THREAD

**Issue by luisapace** [xtuc/webassemblyjs#806]
Hi, my team would use this package and to approve that I've to verify all its licenses; now I see that:

- the package.json at https://github.com/xtuc/webassemblyjs/blob/v1.7.11/packages/dce/package.json states MIT
- the readme at https://github.com/xtuc/webassemblyjs/tree/v1.7.11/packages/dce states GPL V2.

Could you please confirm what is the license and if there is any module under GPL V2 and if so what is?

Thanks.

**Comment by xtuc** [comment]
the dce package is using MIT, I removed the confusing mention of GPL v2 in the readme https://github.com/xtuc/webassemblyjs/tree/master/packages/dce.
