### ISSUE TITLE
Contradicting License Statements

### ISSUE THREAD

**Issue by stefan-hdt** [xtuc/webassemblyjs#808]
I have a short question regarding the package "leb128" of this project. In https://github.com/xtuc/webassemblyjs/blob/v1.8.5/packages/leb128/LICENSE.txt, the copyright holder is "Copyright 2012 The Obvious Corporation. http://obvious.com/" with license Apache-2.0. In https://github.com/xtuc/webassemblyjs/blob/v1.8.5/packages/leb128/package.json, the MIT license is stated as applicable license.

Which license is correct for the package "leb128"?

**Comment by xtuc** [comment]
This is a mistake the leb128 should be under Apache-2.0
