### ISSUE TITLE
cloneNode makes a shallow copy

### ISSUE THREAD

**Issue by mtorp** [xtuc/webassemblyjs#809]
I've noticed that [cloneNode](https://github.com/xtuc/webassemblyjs/blob/master/packages/ast/src/clone.js) makes a shallow copy of the node. I find that a bit surprising. For example, one of the side-effects is that wasm-edit will not identify a node as changed if you only make deep edits. 

Would it be possible to use a deep clone instead? Alternatively the API of wasm-edit could be changed such that the user has to manually mark a node as edited?

**Comment by xtuc** [comment]
Yes indeed this is a bug. It should be a deep clone. Would you mind sending a PR to address that?
