### ISSUE TITLE
How can I load a json to a AST?

### ISSUE THREAD

**Issue by Chehx** [xtuc/webassemblyjs#869]
Currently, I could use wasm-parer to parse a WASM file, and then get an AST tree, which could be easily converted and stored in a JSON file.

```
fs.writeFile(outputFilename, JSON.stringify(ast, null, 4), function(err) {
    if(err) {
      console.log(err);
    } else {
      console.log("JSON saved to " + outputFilename);
    }
});
```

However, how do I to load such json file and convert this to an AST based on the wasm-parser?

**Comment by Chehx** [comment]
When I use general way to parse:

```
let rawdata = fs.readFileSync('./tmp/test2.json');
let test_ast = JSON.parse(rawdata);
```

This would raise an error:

let test_ast = JSON.parse(rawdata);
                    ^

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at file:///c:/Users/cheha/Desktop/Wasm/JSembed/test.mjs:24:21
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

**Comment by xtuc** [comment]
The JSON seems to be invalid and I don't think it's related to our AST. Did you figure out the issue?

**Comment by Chehx** [comment]
> The JSON seems to be invalid and I don't think it's related to our AST. Did you figure out the issue?

Yes, you're right. This issue seems to be related to the file reading stream, after I divide the write and read processing into 2 parts, it works! 

And if convenient, could you give me an example of how to operate the AST tree with this package, there is a limited document and it's hard for me to figure out what I could do.

**Comment by xtuc** [comment]
Sure, an example is https://github.com/xtuc/webassemblyjs/tree/master/packages/dce (package itself is deprecated). https://www.npmjs.com/package/@webassemblyjs/ast allows you to work with the AST tree.

**Comment by Chehx** [comment]
> Sure, an example is https://github.com/xtuc/webassemblyjs/tree/master/packages/dce (package itself is deprecated). https://www.npmjs.com/package/@webassemblyjs/ast allows you to work with the AST tree.

Im so appreciated that! That's what I need!
Many thanks!

**Comment by Chehx** [comment]
> Sure, an example is https://github.com/xtuc/webassemblyjs/tree/master/packages/dce (package itself is deprecated). https://www.npmjs.com/package/@webassemblyjs/ast allows you to work with the AST tree.

Im so appreciated that! That's what I need!
Many thanks!
