### ISSUE TITLE
wasm/wast-parser inconsistency: "Mem" vs "Memory"

### ISSUE THREAD

**Issue by mitschabaude** [xtuc/webassemblyjs#956]
The statement `(export "memory" (memory 0))` gets parsed by wast-parser to an AST node with `node.descr.type` equal to `"Memory"`. On the other hand, wasm-parser produces `node.descr.type` equal to `"Mem"`.

I thought I'd open an issue because I'm not sure such inconsistencies are wanted.

**Comment by xtuc** [comment]
Indeed that's not ideal. Would you mind sending a PR to rename Mem to Memory?

**Comment by mitschabaude** [comment]
Will do!
